###########################################################
# Persistent Volume Claim template for IBM Block CSI Driver
# All the <VALUE> fields must be set
###########################################################

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: <NAME>
# spec:
#   volumeMode: <VOLUMEMODE>   # optional - possible values: Filesystem/Block (default=Filesystem)
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: <STORAGE_SIZE_VALUE>
  storageClassName: <STORAGE_CLASS_NAME>
#   dataSource:                # optinal if creating clone
#     name: <SOURCE_CLONE_NAME>
#     kind: PersistentVolumeClaim
